"""Initial migration

Revision ID: 00c6af94718d
Revises: 
Create Date: 2025-01-18 16:29:50.510025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c6af94718d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert-rules_id', table_name='alert-rules', postgresql_using='prefix')
    op.create_index(op.f('ix_alert-rules_id'), 'alert-rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert-rules_id'), table_name='alert-rules')
    op.create_index('ix_alert-rules_id', 'alert-rules', [sa.text('id NULLS FIRST')], unique=False, postgresql_using='prefix')
    # ### end Alembic commands ###
