"""Initial migration

Revision ID: 954dd6903916
Revises: 
Create Date: 2025-01-17 14:07:30.393975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954dd6903916'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_id', table_name='alerts', postgresql_using='prefix')
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.create_index('ix_alerts_id', 'alerts', [sa.text('id NULLS FIRST')], unique=False, postgresql_using='prefix')
    # ### end Alembic commands ###
